services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PORT=5000
      - DATA_CLEANER_PORT=${DATA_CLEANER_PORT}
      - DATA_PREPROCESSOR_PORT=${DATA_PREPROCESSOR_PORT}
      - DATA_NORMALIZER_PORT=${DATA_NORMALIZER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    depends_on:
      data-cleaner:
        condition: service_healthy
      data-preprocessor:
        condition: service_healthy
      data-normalizer:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  data-cleaner:
    build: ./containers/data-cleaner
    container_name: data-cleaner
    expose:
      - "${DATA_CLEANER_PORT}"
    environment:
      - PORT=${DATA_CLEANER_PORT}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${DATA_CLEANER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-preprocessor:
    build: ./containers/data-preprocessor
    container_name: data-preprocessor
    expose:
      - "${DATA_PREPROCESSOR_PORT}"
    environment:
      - PORT=${DATA_PREPROCESSOR_PORT}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${DATA_PREPROCESSOR_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-normalizer:
    build: ./containers/data-normalizer
    container_name: data-normalizer
    expose:
      - "${DATA_NORMALIZER_PORT}"
    environment:
      - PORT=${DATA_NORMALIZER_PORT}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${DATA_NORMALIZER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    name: ${DOCKER_NETWORK} 